### ISSUE TITLE
problem: CLIPIQA is not in the model registry

### ISSUE THREAD

**Issue by YaoShunyu19** [IceClear/CLIP-IQA#1]
Hi!
I try to run clipiqa_single_image_demo.py, but it tells me "CLIPIQA is not in the model registry".
Could you please tell me how to fix this problem? Thanks!

**Comment by IceClear** [comment]
I guess you may use the wrong [mmedit](https://github.com/IceClear/CLIP-IQA/tree/main/mmedit) package. you should install the package in this repo using `pip install -v -e .` .

**Comment by YaoShunyu19** [comment]
The problem is solved. Thank you!

**Comment by kumarkaushik1995** [comment]
Hi, @YaoShunyu19 Can you explain how you solved this problem? Im having the same issue. I am having trouble installing mmcv-full. Do you have any solution?

**Comment by YaoShunyu19** [comment]
I just run `pip install -v -e .`

**Comment by kumarkaushik1995** [comment]
@YaoShunyu19 Thank you for the response, the mmcv-full==1.5.0 installation from the requirements file fails to build. Did you face any issues during installation?

**Comment by YaoShunyu19** [comment]
@kumarkaushik1995 Sorry... I follow the readme and build the mmcv-full successfully.
Maybe you can try pip install the packages respectively? Using `pip install  lmdb` ,`pip install mmcv-full==1.5.0` rather than `pip install -r requirements.txt`?
