### ISSUE TITLE
Code without OpenMMLab integration?

### ISSUE THREAD

**Issue by justlike-prog** [IceClear/CLIP-IQA#13]
@IceClear Any chance to get the code without using OpenMMLab? Would make it easier for experimenting. Thanks for the awesome work by the way.

**Comment by justlike-prog** [comment]
Or rather it would be nice to know which pytorch transforms one needs to reproduce the results given an image. The OpenMMLab transforms are quite cryptic and differ from the torchvision ones. Were the results of paper based on the mmcv transforms? Right now I am doing the following, but my results are scewed a bit: 


```
transform = transforms.Compose([transforms.ToTensor(),
                            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
                            ])

img = Image.open("./test.jpeg").convert("RGB")
img = transform(img)
img = img.unsqueeze(0)
```

**Comment by IceClear** [comment]
Hi, you may refer to [IQA-pytorch](https://github.com/chaofengc/IQA-PyTorch), which also supports CLIP-IQA :)
It should be easy to use.

**Comment by sunhaha123** [comment]
> Hi, you may refer to [IQA-pytorch](https://github.com/chaofengc/IQA-PyTorch), which also supports CLIP-IQA :) It should be easy to use.

结果根本就对不齐，我是真想用，给气笑了
