### ISSUE TITLE
Pretrained model iter80000.pth not loading

### ISSUE THREAD

**Issue by kumarkaushik1995** [IceClear/CLIP-IQA#3]
Hi @IceClear , I am trying to run the demo for a single image, but the pretrained model provided is taking forever to load. Infact, doesn't load at all. 

This is the line with the issue:

```
model = init_model(
        args.config, args.checkpoint, device=torch.device('cuda', args.device))
```

This is the output I get:

```
Initializing a generic context
Initial context: "X X X X X X X X X X X X X X X X"
Number of context words (tokens): 16
2023-02-20 03:16:18.505897: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-20 03:16:18.939280: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
```

After which it just doesn't complete loading. 
Im using config file: `./configs/clipiqa/clipiqa_coop_koniq.py`
and checkpoint: `./iter_80000.pth` as provided and mentioned. 

Please advice.

**Comment by IceClear** [comment]
Hi, thanks for your interest. I am not sure what the problem is since I did not see any bugs reported from your provided info. It seems that the process is stacked somewhere. But the code is able to run on my device. More details are expected on your device I think.

**Comment by kumarkaushik1995** [comment]
@IceClear , thank you for your response. I am using sagemaker or Colab to work on models which usually come with a default python 3.8 or 3.9 installations. But it looks like a majority of installation issues are happening because the repo uses python 3.6 and I am using 3.8. Can you update the repo to use 3.8 instead or maybe upload a colab demo notebook? That would make it really useful. python 3.6 is super old and comes with security issues. Thank you.

**Comment by IceClear** [comment]
I am busy with my ICCV submission. I will update the repo after the DDL.

**Comment by kumarkaushik1995** [comment]
@IceClear thank you for the reply. I am looking forward to the update.  Good luck with the conference!

**Comment by IceClear** [comment]
@kumarkaushik1995 
Hi, now the project has been upgraded to 3.8 and should work.
You may have a try.
